### ISSUE TITLE
Protein count alternates

### ISSUE THREAD

**Issue by dominik-kopczynski** [compomics/peptide-shaker-2.0-issue-tracker#58]
In PeptideShaker 2.0, when I execute several times the same experiment with the same parameters and the same input files, I get different confident / doubtful protein counts.

**Comment by hbarsnes** [comment]
The problem is the mass deviation quality control filter, specifically the precrusorMzErrorStat filter. It returns different p-values for the same precursor mz and mz error values.

See line 319 in com.compomics.util.experiment.identification.filtering.AssumptionFilter

If I instead use the precrusorMzErrorDa filter, the confident/doubtful protein counts stay the same across multiple project loadings.

**Comment by hbarsnes** [comment]
Should be fixed in https://github.com/compomics/peptide-shaker/commit/338e81d5ae589a35663daf8310fc1996c0fabd82.

**Comment by dominik-kopczynski** [comment]
Thank you, but after pulling and compiling the freshest versions of SG and PS, I still have the same issue, but this time at the total number of proteins. The number hops in the qExactive example (searched by xTandem) between 1334 and 1336 proteins in total. The other values remain stable.

**Comment by hbarsnes** [comment]
Should be fixed in https://github.com/compomics/peptide-shaker/commit/cea04f0e08465f78efe9c4794ad1915bfb9697dc.
